server.port: 8088
spring:
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/school-management-system?serverTimezone=UTC
    username: school-management-system
    password: Rhysand6651